steps:
  # 1. Собираем образ Docker из папки backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: 
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ecoprint-new/ecoprint-api:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  # 2. Отправляем собранный образ в кэш Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ecoprint-new/ecoprint-api:$COMMIT_SHA'

  # 3. АВТОМАТИЧЕСКИ обновляем сервер Cloud Run новым кодом
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecoprint-api'
      - '--image'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ecoprint-new/ecoprint-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west3'

images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ecoprint-new/ecoprint-api:$COMMIT_SHA'
