# Generated by Django 6.0.3 on 2026-03-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компании',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('not-ready', 'Не готов'), ('in-progress', 'В процессе'), ('ready', 'Готово')], default='not-ready', max_length=20, verbose_name='Статус заказа')),
                ('is_received', models.BooleanField(default=False, verbose_name='Получен клиентом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('polygraphy', 'Полиграфия'), ('packaging', 'Упаковка'), ('souvenirs', 'Сувениры'), ('large-format', 'Широкоформатная печать')], max_length=50, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (FontAwesome)')),
            ],
            options={
                'verbose_name': 'Товар (шаблон)',
                'verbose_name_plural': 'Товары (шаблоны)',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='Token Telegram-бота')),
                ('chat_id', models.CharField(blank=True, max_length=255, verbose_name='Chat ID')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('status', models.CharField(choices=[('not-ready', 'Не готов'), ('in-progress', 'В процессе'), ('ready', 'Готово')], default='not-ready', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Аватар')),
                ('sound_notifications', models.BooleanField(default=True, verbose_name='Звук')),
                ('popup_notifications', models.BooleanField(default=True, verbose_name='Всплывающие окна')),
                ('day_before_notifications', models.BooleanField(default=True, verbose_name='Напоминание за день')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
