# Generated by Django 6.0.3 on 2026-03-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_is_archived_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
