# Generated by Django 5.1.6 on 2026-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Супер Админ'), ('manager', 'Менеджер'), ('worker', 'Работник')], default='worker', max_length=20, verbose_name='Роль в системе'),
        ),
    ]
