# Generated by Django 5.1.6 on 2026-04-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Товары заказа'},
        ),
    ]
